name: Deploy Zip to Repository

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List files for verification
        run: ls -la

      - name: Extract ZIP file
        run: |
          # החלף את 'your-file.zip' בשם קובץ הזיפ שלך
          unzip -o fileexplorer_fixed_project.zip -d ./extracted-files

      - name: Deploy Files
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./extracted-files
